# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tpsp_bs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='netbars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatdate', models.DateField(auto_created=True)),
                ('gid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='platforminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformname', models.CharField(blank=True, max_length=40, null=True)),
                ('puturl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='plugin_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('tpsp_taskid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=256)),
                ('updated_at', models.DateField()),
                ('deleted_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='plugin_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('ftype', models.IntegerField(choices=[(1, '\u914d\u7f6e'), (2, '\u6587\u4ef6')], default=1, verbose_name='\u7c7b\u578b')),
                ('fpath', models.FileField(blank=True, null=True, upload_to=tpsp_bs.models.get_plugfile_path)),
                ('curl', models.URLField()),
                ('version', models.CharField(max_length=20)),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='plugin_temp_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('dec', models.CharField(max_length=40)),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='reslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileurl', models.FileField(blank=True, null=True, upload_to=tpsp_bs.models.get_file_path)),
                ('creatdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['creatdate'],
            },
        ),
        migrations.CreateModel(
            name='t_netbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatdate', models.DateField(auto_created=True)),
                ('gid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_taskname', models.CharField(max_length=40)),
                ('resnum', models.IntegerField()),
                ('creatdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_email', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='t_taskput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_taskputname', models.CharField(max_length=40)),
                ('t_reslistput', models.CharField(max_length=32)),
                ('state', models.IntegerField(choices=[(0, '\u53d1\u5e03\u4e2d'), (1, 'remove')], default=0)),
                ('creatdate', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('git', models.ManyToManyField(to='tpsp_bs.t_netbar')),
                ('t_taskid', models.ManyToManyField(to='tpsp_bs.t_task')),
            ],
        ),
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50)),
                ('user_email', models.IntegerField(choices=[(0, '\u65e0'), (1, '\u9ed8\u8ba4\u53d1\u4ef6\u4eba'), (2, '\u9ed8\u8ba4\u6536\u4ef6\u4eba'), (3, '\u53d1\u4ef6\u4eba'), (4, '\u6536\u4ef6\u4eba')], default=0, verbose_name='\u90ae\u4ef6\u5173\u8054')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='plugin_templation',
            fields=[
                ('plugin_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpsp_bs.plugin_base')),
                ('plugin_config', models.TextField(max_length=256)),
            ],
            bases=('tpsp_bs.plugin_base',),
        ),
        migrations.CreateModel(
            name='plugins',
            fields=[
                ('plugin_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpsp_bs.plugin_base')),
                ('version', models.CharField(max_length=20)),
            ],
            bases=('tpsp_bs.plugin_base',),
        ),
        migrations.AddField(
            model_name='reslist',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.t_task'),
        ),
        migrations.AddField(
            model_name='plugin_base',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.platforminfo'),
        ),
        migrations.AddField(
            model_name='plugin_base',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='netbars',
            name='platformid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.platforminfo'),
        ),
        migrations.AlterUniqueTogether(
            name='reslist',
            unique_together=set([('taskid', 'creatdate')]),
        ),
        migrations.AddField(
            model_name='plugin_temp_config',
            name='plugin_tempid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.plugin_templation'),
        ),
        migrations.AddField(
            model_name='plugin_file',
            name='pluginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.plugins'),
        ),
    ]
