# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tpsp_bs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileurl', models.FileField(blank=True, null=True, upload_to=tpsp_bs.models.get_file_path)),
                ('creatdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_netbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatdate', models.DateField(auto_created=True)),
                ('gid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatdate', models.DateField(auto_created=True)),
                ('t_taskname', models.CharField(max_length=40)),
                ('resnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_taskput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_taskputname', models.CharField(max_length=40)),
                ('t_reslistput', models.CharField(max_length=32)),
                ('state', models.IntegerField(choices=[(0, '\u53d1\u5e03\u4e2d'), (1, 'remove')], default=0)),
                ('creatdate', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('git', models.ManyToManyField(to='tpsp_bs.t_netbar')),
                ('t_taskid', models.ManyToManyField(to='tpsp_bs.t_task')),
            ],
        ),
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('user_email', models.IntegerField(choices=[(0, '\u65e0'), (1, '\u9ed8\u8ba4\u53d1\u4ef6\u4eba'), (2, '\u9ed8\u8ba4\u6536\u4ef6\u4eba'), (3, '\u53d1\u4ef6\u4eba'), (4, '\u6536\u4ef6\u4eba')], default=0, verbose_name='\u90ae\u4ef6\u5173\u8054')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='t_task',
            name='task_email',
            field=models.ManyToManyField(to='tpsp_bs.t_user'),
        ),
        migrations.AddField(
            model_name='reslist',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpsp_bs.t_task'),
        ),
    ]
