# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tpsp_bs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_task',
            name='creatdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
