# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpsp_bs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='password',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
